=== kennykarnama/fsistoolx/ilfreporter-0.0.1/xsd/KPMRRiskProfileConf.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:kpmr="http://example.com/kpmr"
        targetNamespace="http://example.com/kpmr"
        elementFormDefault="qualified">

    <xs:element name="RiskProfileConf" >
        <xs:complexType>
            <xs:sequence>
                <xs:element type="kpmr:AggregationConfig" name="aggregationConfig" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            aggregationConfig defines configuration to aggregate risk profile tree nodes to derive overall risk profile score and rating.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>

    <xs:complexType name="AggregationConfig">
        <xs:sequence>
            <xs:element name="risikoName" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        risikoName defines risk profile name, e.g. Risiko Kredit etc.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="score_rule" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Element score_rule defines user script that needs to be evaluated in order to derive the score. 
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="rating_rule" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Element rating_rule defines user script that needs to evaluated in order to derive the rating. 
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            
            <xs:element name="rating_to_score" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Rating to score mapping before it will be transformed into exprtk
                    </xs:documentation>
                </xs:annotation>
            </xs:element>

            <xs:element name="computed_weighted_score" type="xs:decimal" minOccurs="0"></xs:element>
            <xs:element name="computed_rating" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== kennykarnama/fsistoolx/ilfreporter-0.0.1/testdata/kpmr_riskpro_conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<RiskProfileConf xmlns="http://example.com/kpmr"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://example.com/kpmr ../xsd/KPMRRiskProfileConf.xsd">
   <aggregationConfig>
      <risikoName>Risiko Kredit</risikoName>
      <score_rule>
          <![CDATA[
              var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Kredit']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }

              
             return total * 1.0;
          ]]>
      </score_rule>
      <rating_rule>
            <![CDATA[
            var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Kredit']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }
              
              var x = total;

              print(threshold);
              
              var r = ratingByThreshold(threshold, x);
              
              return r;
            
            ]]>
       </rating_rule>
       <rating_to_score>
             <![CDATA[
             5 : x<=40
4:  40 < x <=55
3:  55 < x <=70
2:  70 < x <=85
1:  85 < x <=100
             ]]>
       </rating_to_score>
   </aggregationConfig>
   <aggregationConfig>
      <risikoName>Risiko Operasional</risikoName>
      <score_rule>
          <![CDATA[
              var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Operasional']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }

              
             return total * 1.0;
          ]]>
      </score_rule>
      <rating_rule>
            <![CDATA[
            var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Operasional']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }
              
              var x = total;
              
              var r = ratingByThreshold(threshold, x);
              
              return r;
            
            ]]>
       </rating_rule>
       <rating_to_score>
             <![CDATA[
             5 : x<=40
4:  40 < x <=55
3:  55 < x <=70
2:  70 < x <=85
1:  85 < x <=100
             ]]>
       </rating_to_score>
   </aggregationConfig>
   <aggregationConfig>
      <risikoName>Risiko Hukum</risikoName>
      <score_rule>
          <![CDATA[
              var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Hukum']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }

              
             return total * 1.0;
          ]]>
      </score_rule>
      <rating_rule>
            <![CDATA[
            var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Hukum']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }
              
              var x = total;
              
              var r = ratingByThreshold(threshold, x);
              
              return r;
            
            ]]>
       </rating_rule>
       <rating_to_score>
             <![CDATA[
             5 : x<=40
4:  40 < x <=55
3:  55 < x <=70
2:  70 < x <=85
1:  85 < x <=100
             ]]>
       </rating_to_score>
   </aggregationConfig>
   <aggregationConfig>
      <risikoName>Risiko Intragrup</risikoName>
      <score_rule>
          <![CDATA[
              var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Intragrup']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }

              
             return total * 1.0;
          ]]>
      </score_rule>
      <rating_rule>
            <![CDATA[
            var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Intragrup']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }
              
              var x = total;
              
              var r = ratingByThreshold(threshold, x);
              
              return r;
            
            ]]>
       </rating_rule>
       <rating_to_score>
             <![CDATA[
             5 : x<=40
4:  40 < x <=55
3:  55 < x <=70
2:  70 < x <=85
1:  85 < x <=100
             ]]>
       </rating_to_score>
   </aggregationConfig>
   <aggregationConfig>
      <risikoName>Risiko Asuransi</risikoName>
      <score_rule>
          <![CDATA[
              var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Asuransi']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }

              
             return total * 1.0;
          ]]>
      </score_rule>
      <rating_rule>
            <![CDATA[
            var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Asuransi']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }
              
              var x = total;
              
              var r = ratingByThreshold(threshold, x);
              
              return r;
            
            ]]>
       </rating_rule>
       <rating_to_score>
             <![CDATA[
             5 : x<=40
4:  40 < x <=55
3:  55 < x <=70
2:  70 < x <=85
1:  85 < x <=100
             ]]>
       </rating_to_score>
   </aggregationConfig>
   <aggregationConfig>
      <risikoName>Risiko Investasi</risikoName>
      <score_rule>
          <![CDATA[
              var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Investasi']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }

              
             return total * 1.0;
          ]]>
      </score_rule>
      <rating_rule>
            <![CDATA[
            var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Investasi']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }
              
              var x = total;
              
              var r = ratingByThreshold(threshold, x);
              
              return r;
            
            ]]>
       </rating_rule>
       <rating_to_score>
             <![CDATA[
             5 : x<=40
4:  40 < x <=55
3:  55 < x <=70
2:  70 < x <=85
1:  85 < x <=100
             ]]>
       </rating_to_score>
   </aggregationConfig>
   <aggregationConfig>
      <risikoName>Risiko Imbal Hasil</risikoName>
      <score_rule>
          <![CDATA[
              var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Imbal Hasil']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }

              
             return total * 1.0;
          ]]>
      </score_rule>
      <rating_rule>
            <![CDATA[
            var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Imbal Hasil']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }
              
              var x = total;
              
              var r = ratingByThreshold(threshold, x);
              
              return r;
            
            ]]>
       </rating_rule>
       <rating_to_score>
             <![CDATA[
             5 : x<=40,
4:  40 < x <=55
3:  55 < x <=70
2:  70 < x <=85
1:  85 < x <=100
             ]]>
       </rating_to_score>
   </aggregationConfig>
   <aggregationConfig>
      <risikoName>Risiko Likuiditas</risikoName>
      <score_rule>
          <![CDATA[
              var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Likuiditas']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }

              
             return total * 1.0;
          ]]>
      </score_rule>
      <rating_rule>
            <![CDATA[
            var nodes = retrieveNodesByXpath("//Node[risiko_name='Risiko Likuiditas']");
              var total = 0.0;

              var converted = kpmrNodeTypeAsChaiVar(nodes);

              for (c : converted) {
                total += c["Computed_Score"] * 1.0;
              }
              
              var x = total;
              
              var r = ratingByThreshold(threshold, x);
              
              return r;
            
            ]]>
       </rating_rule>
       <rating_to_score>
             <![CDATA[
             5 : x<=40
4:  40 < x <=55
3:  55 < x <=70
2:  70 < x <=85
1:  85 < x <=100
             ]]>
       </rating_to_score>
   </aggregationConfig>
