=== kennykarnama/fsistoolx/ilfreporter-0.0.1/xsd/KPMRRiskProfile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:kpmr="http://example.com/kpmr"
        targetNamespace="http://example.com/kpmr"
        elementFormDefault="qualified">
  
  <!-- Root Element -->
  <xs:element name="kpmr_risk_profile_tree">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="node" type="kpmr:NodeType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Node Type (recursive structure) -->
  <xs:complexType name="NodeType">
    <xs:sequence>
      <xs:element name="risiko_name" type="xs:string"/>
      <xs:element name="profile_id" type="xs:string"/>
      <xs:element name="assessment_factor" type="xs:string"/>
      <xs:element name="derived_from" type="xs:string"/>
      <xs:element name="threshold" type="xs:string"/>
      <xs:element name="input_type" type="xs:string"/>
      <xs:element name="source_reference" type="xs:string"/>
      <xs:element name="calculation_logic" type="xs:string"/>
      <xs:element name="risk_id" type="xs:integer"/>
      <xs:element name="id" type="xs:integer"/>
      <xs:element name="weight" type="xs:decimal" minOccurs="0"/>
      <xs:element name="score_formula" minOccurs="0" type="xs:string" />

      <xs:element name="rating_to_score" minOccurs="0" type="xs:string">
      </xs:element>

      <xs:element name="rating_rule" minOccurs="0" type="xs:string">
       
      </xs:element>

      <xs:element name="score_rule" minOccurs="0" type="xs:string">
       
      </xs:element>

      <xs:element name="value_rule" minOccurs="0" type="xs:string">
       
      </xs:element>

      <xs:element name="computed_rating" type="xs:string" minOccurs="0"></xs:element>
      <xs:element name="computed_score" type="xs:string" minOccurs="0"></xs:element>
      <xs:element name="computed_value" type="xs:string" minOccurs="0"></xs:element>
      <xs:element name="computed_weighted_score" type="xs:string" minOccurs="0"></xs:element>

      <xs:element name="children" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="node" type="kpmr:NodeType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== kennykarnama/fsistoolx/ilfreporter-0.0.1/testdata/kpmr_riskpro_s1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<kpmr_risk_profile_tree xmlns="http://example.com/kpmr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.com/kpmr ../xsd/KPMRRiskProfile.xsd">
  <node>
    <risiko_name>Risiko Investasi</risiko_name>
    <profile_id>RK11000000</profile_id>
    <assessment_factor/>
    <derived_from/>
    <threshold/>
    <input_type/>
    <source_reference/>
    <calculation_logic/>
    <risk_id>0</risk_id>
    <id>586</id>
    <weight>0</weight>
    <score_formula/>
    <children>
      <node>
        <risiko_name>Risiko Investasi</risiko_name>
        <profile_id>RK11001000</profile_id>
        <assessment_factor>Tata Kelola (Risk Governance)</assessment_factor>
        <derived_from>Risk Profile</derived_from>
        <threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</threshold>
        <input_type>system</input_type>
        <source_reference/>
        <calculation_logic>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</calculation_logic>
        <risk_id>0</risk_id>
        <id>587</id>
        <weight>25</weight>
        <score_formula/>
        <children>
          <node>
            <risiko_name>Risiko Investasi</risiko_name>
            <profile_id>RK11001001</profile_id>
            <assessment_factor>Perumusan tingkat risiko yang akan diambil (risk appetite) dan toleransi risiko (risk tolerance)</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold>Value = 1
Value = 2
Value = 3
Value = 4
Value = 5</threshold>
            <input_type>system</input_type>
            <source_reference>SK11001001</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>0</risk_id>
            <id>588</id>
            <weight>50</weight>
            <score_formula/>
          </node>
          <node>
            <risiko_name>Risiko Investasi</risiko_name>
            <profile_id>RK11001002</profile_id>
            <assessment_factor>Kecukupan pengawasan aktif oleh Dewan Komisaris dan Direksi termasuk pelaksanaan kewenangan dan tanggung jawab Dewan Komisaris dan Direksi.</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold>Value = 1
Value = 2
Value = 3
Value = 4
Value = 5</threshold>
            <input_type>system</input_type>
            <source_reference>SK11001002</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>0</risk_id>
            <id>589</id>
            <weight>50</weight>
            <score_formula/>
          </node>
        </children>
      </node>
      <node>
        <risiko_name>Risiko Investasi</risiko_name>
        <profile_id>RK11003000</profile_id>
        <assessment_factor>Proses Manajemen Risiko, SIM dan SDM</assessment_factor>
        <derived_from>Risk Profile</derived_from>
        <threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</threshold>
        <input_type>system</input_type>
        <source_reference/>
        <calculation_logic>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</calculation_logic>
        <risk_id>0</risk_id>
        <id>594</id>
        <weight>25</weight>
        <score_formula/>
        <children>
          <node>
            <risiko_name>Risiko Investasi</risiko_name>
            <profile_id>RK11003001</profile_id>
            <assessment_factor>Proses identifikasi, pengukuran, pemantauan, dan pengendalian risiko Identfikasi</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold>Value = 1
Value = 2
Value = 3
Value = 4
Value = 5</threshold>
            <input_type>system</input_type>
            <source_reference>SK11003001</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>0</risk_id>
            <id>595</id>
            <weight>33.329999999999998</weight>
            <score_formula/>
          </node>
          <node>
            <risiko_name>Risiko Investasi</risiko_name>
            <profile_id>RK11003002</profile_id>
            <assessment_factor>Kecukupan sistem informasi Manajemen Risiko</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold>Value = 1
Value = 2
Value = 3
Value = 4
Value = 5</threshold>
            <input_type>system</input_type>
            <source_reference>SK11003002</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>0</risk_id>
            <id>596</id>
            <weight>33.329999999999998</weight>
            <score_formula/>
          </node>
          <node>
            <risiko_name>Risiko Investasi</risiko_name>
            <profile_id>RK11003003</profile_id>
            <assessment_factor>Kecukupan kuantitas dan kualitas sumber daya manusia dalam mendukung efektivitas proses Manajemen Risiko</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold>Value = 1
Value = 2
Value = 3
Value = 4
Value = 5</threshold>
            <input_type>system</input_type>
            <source_reference>SK11003003</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>0</risk_id>
            <id>597</id>
            <weight>33.329999999999998</weight>
            <score_formula/>
          </node>
        </children>
      </node>
      <node>
        <risiko_name>Risiko Investasi</risiko_name>
        <profile_id>RK11004000</profile_id>
        <assessment_factor>Sistem Pengendalian</assessment_factor>
        <derived_from>Risk Profile</derived_from>
        <threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</threshold>
        <input_type>system</input_type>
        <source_reference/>
        <calculation_logic>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</calculation_logic>
        <risk_id>0</risk_id>
        <id>598</id>
        <weight>25</weight>
        <score_formula/>
        <children>
          <node>
            <risiko_name>Risiko Investasi</risiko_name>
            <profile_id>RK11004001</profile_id>
            <assessment_factor>Kecukupan Sistem Pengendalian Intern</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold>Value = 1
Value = 2
Value = 3
Value = 4
Value = 5</threshold>
            <input_type>system</input_type>
            <source_reference>SK11004001</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>0</risk_id>
            <id>599</id>
            <weight>50</weight>
            <score_formula/>
          </node>
          <node>
            <risiko_name>Risiko Investasi</risiko_name>
            <profile_id>RK11004002</profile_id>
            <assessment_factor>Kecukupan kaji ulang oleh pihak independen dalam Bank, baik oleh Satuan Kerja Manajemen Risiko (SKMR) maupun oleh Satuan Kerja Audit Intern (SKAI)</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold>Value = 1
Value = 2
Value = 3
Value = 4
Value = 5</threshold>
            <input_type>system</input_type>
            <source_reference>SK11004002</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>0</risk_id>
            <id>600</id>
            <weight>50</weight>
            <score_formula/>
          </node>
        </children>
      </node>
      <node>
        <risiko_name>Risiko Investasi</risiko_name>
        <profile_id>RK11002000</profile_id>
        <assessment_factor>Kerangka Manajemen Risiko</assessment_factor>
        <derived_from>Risk Profile</derived_from>
        <threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</threshold>
        <input_type>system</input_type>
        <source_reference/>
        <calculation_logic>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</calculation_logic>
