<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE select_risiko_name_threshold_calculation_logic_from_kpmr_risk_profile_edge_where_profile_id_is_null_and_threshold_is_not_null [
  <!ELEMENT select_risiko_name_threshold_calculation_logic_from_kpmr_risk_profile_edge_where_profile_id_is_null_and_threshold_is_not_null (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (risiko_name?,threshold?,calculation_logic?)+>
  <!ELEMENT risiko_name (#PCDATA)>
  <!ELEMENT threshold (#PCDATA)>
  <!ELEMENT calculation_logic (#PCDATA)>
]>
<select_risiko_name_threshold_calculation_logic_from_kpmr_risk_profile_edge_where_profile_id_is_null_and_threshold_is_not_null>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Operasional</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Hukum</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Intragrup</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Asuransi</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Investasi</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Imbal Hasil</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Likuiditas</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Reputasi</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Stratejik</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kepatuhan</risiko_name>
    <threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</threshold>
    <calculation_logic>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</calculation_logic>
  </DATA_RECORD>
</select_risiko_name_threshold_calculation_logic_from_kpmr_risk_profile_edge_where_profile_id_is_null_and_threshold_is_not_null>
