<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kpmr_source [
  <!ELEMENT kpmr_source (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (id?,code?,risk_id?,assesment_factor?,pic?,state?,tx_id?,valid_from?,valid_to?,created_at?,created_by?,updated_at?,updated_by?,numeric_id?)+>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT code (#PCDATA)>
  <!ELEMENT risk_id (#PCDATA)>
  <!ELEMENT assesment_factor (#PCDATA)>
  <!ELEMENT pic (#PCDATA)>
  <!ELEMENT state (#PCDATA)>
  <!ELEMENT tx_id (#PCDATA)>
  <!ELEMENT valid_from (#PCDATA)>
  <!ELEMENT valid_to (#PCDATA)>
  <!ELEMENT created_at (#PCDATA)>
  <!ELEMENT created_by (#PCDATA)>
  <!ELEMENT updated_at (#PCDATA)>
  <!ELEMENT updated_by (#PCDATA)>
  <!ELEMENT numeric_id (#PCDATA)>
]>
<kpmr_source>
  <DATA_RECORD>
    <id>2426624f-b9ce-465e-95f9-e7b1ffd5841e</id>
    <code>SK01001004</code>
    <risk_id>8</risk_id>
    <assesment_factor>Pelaksanaan tugas Dewan Komisaris dan Direksi LJK secara keseluruhan untuk Risiko kredit</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>6ccbc728-5eb8-4778-b62c-a55a7f18fe02</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>1</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>0638434e-b454-49af-a230-4583d0247cf8</id>
    <code>SK01002001</code>
    <risk_id>8</risk_id>
    <assesment_factor>Fungsi Manajemen Risiko kredit pada LJK dalam Konglomerasi Keuangan memiliki tugas dan tanggung jawab yang jelas, serta telah berjalan independen</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>d9b7743f-bb36-4f59-bca5-2934451bc19c</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>2</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>6bbea8ff-8e6b-41c8-a79a-595b3fe9efdc</id>
    <code>SK01002002</code>
    <risk_id>8</risk_id>
    <assesment_factor>Strategi perkreditan atau pembiayaan dan kesesuaiannya dengan tingkat Risiko yang akan diambil dan toleransi Risiko kredit</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>ec640add-6b3c-4e37-a923-fbd1ad0c64f5</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>3</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>9d46832e-d1ed-4641-adff-8f9795ce955a</id>
    <code>SK01002003</code>
    <risk_id>8</risk_id>
    <assesment_factor>Terdapat kebijakan, prosedur, dan limit Risiko kredit untuk seluruh area manajemen Risiko kredit yang diterapkan dan dipahami</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>6e7d510e-19c7-4736-8ee0-6af6e4207a73</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>4</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>7bdf061f-6899-4d9a-9b71-cded2504c50f</id>
    <code>SK01003001</code>
    <risk_id>8</risk_id>
    <assesment_factor>Proses manajemen Risiko kredit oleh LJK dalam Konglomerasi Keuangan dalam mengidentifikasi, mengukur, memantau, dan mengendalikan Risiko kredit</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>00a1fa3d-69e8-4494-806d-f1b89844f06d</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>5</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>51518c36-8ff1-4291-a027-7fca91c0dd60</id>
    <code>SK01003002</code>
    <risk_id>8</risk_id>
    <assesment_factor>Proses penyediaan dana oleh LJK dalam Konglomerasi Keuangan mulai dari proses analisis hingga penanganan aset bermasalah</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>7fb49ec7-df55-4d97-a56a-f74bb05cbfce</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>6</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>75e78847-d936-487f-a69e-97b8ada27bc5</id>
    <code>SK01003003</code>
    <risk_id>8</risk_id>
    <assesment_factor>Sistem pemeringkatan Risiko kredit diterapkan secara konsisten, dan dipahami dengan baik oleh seluruh LJK dalam Konglomerasi Keuangan</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>56cfabd1-0651-40be-856a-15cce5ca1a24</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>7</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>78c00725-1707-4f0f-af05-2f05397f7996</id>
    <code>SK01003004</code>
    <risk_id>8</risk_id>
    <assesment_factor>Terdapat Sistem Informasi Manajemen Terintegrasi (SIMT) untuk Risiko kredit sehingga menghasilkan pelaporan Risiko kredit Konglomerasi Keuangan secara keseluruhan yang komprehensif dan terintegrasi</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>41cbe916-c61c-4922-a6eb-a9eea7ed269b</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>8</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>717fc2e6-14f6-4ec1-ace0-d285cc1d6b99</id>
    <code>SK01003005</code>
    <risk_id>8</risk_id>
    <assesment_factor>Pemenuhan sumber daya manusia pada LJK dalam Konglomerasi Keuangan baik dari sisi kuantitas maupun kompetensi pada fungsi manajemen Risiko kredit</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>d5878a7d-0d3b-4ca1-b9b8-2b8463d4b60d</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>9</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>12ea038e-5e2c-4ee2-8094-5e34d60fb013</id>
    <code>SK01004002</code>
    <risk_id>8</risk_id>
    <assesment_factor>Pelaksanaan kaji ulang secara independen (independent review) untuk Risiko kredit oleh SKAIT baik dari sisi metodologi, frekuensi, maupun pelaporan kepada Dewan Komisaris dan Direksi LJK</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>03482900-7e28-4e30-bee8-657092b0755d</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>10</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>00af78d0-1ff1-47ca-9bd5-c9ca2a0e68f0</id>
    <code>SK01004004</code>
    <risk_id>8</risk_id>
    <assesment_factor>Pelaksanaan tindak lanjut atas hasil kaji ulang independen untuk Risiko kredit</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>02186ce5-6365-4d5d-b82b-bc9852663c64</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>11</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>37e8b2aa-e9b1-4545-b67b-e669a19be572</id>
    <code>SK01001001</code>
    <risk_id>8</risk_id>
    <assesment_factor>Penetapan tingkat Risiko kredit yang akan diambil oleh LJK dan toleransi Risikonya sejalan dengan sasaran strategis dan strategi bisnis LJK secara keseluruhan</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>4040baf4-aba7-437a-a12d-8bcb1d75bfd0</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>2025-12-01 09:19:16.304 +0700</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-01 09:19:16.304 +0700</updated_at>
    <updated_by>301</updated_by>
    <numeric_id>12</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>831010af-fdd0-46ce-a858-56a30d3f9684</id>
    <code>SK01001001</code>
    <risk_id>8</risk_id>
    <assesment_factor>Penetapan tingkat Risiko kredit yang akan diambil oleh LJK dan toleransi Risikonya sejalan dengan sasaran strategis dan strategi bisnis LJK secara keseluruhan</assesment_factor>
    <pic>{"value": "BANK,INSURANCE_COMPANY", "from_col": "COMPANY_TYPE"}</pic>
    <state>PUBLISHED</state>
    <tx_id>4040baf4-aba7-437a-a12d-8bcb1d75bfd0</tx_id>
    <valid_from>2025-12-01 09:19:16.293 +0700</valid_from>
    <valid_to>2025-12-01 09:30:27.800 +0700</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-01 09:30:27.800 +0700</updated_at>
    <updated_by>301</updated_by>
    <numeric_id>13</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>3b85909a-3cae-41d2-bf1c-62c11f7fbb45</id>
    <code>SK01001002</code>
    <risk_id>8</risk_id>
    <assesment_factor>Awareness dan pemahaman Dewan Komisaris dan Direksi LJK mengenai manajemen Risiko kredit</assesment_factor>
    <pic>{"value": "BANK,INSURANCE_COMPANY", "from_col": "COMPANY_TYPE"}</pic>
    <state>PUBLISHED</state>
    <tx_id>501dc4eb-66d8-4092-90af-410d15919650</tx_id>
    <valid_from>2025-12-01 10:03:15.009 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-01 10:03:15.009 +0700</updated_at>
    <updated_by>301</updated_by>
    <numeric_id>14</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>1e802485-f2ee-4b9a-9b92-adb71120e37b</id>
    <code>SK01001002</code>
    <risk_id>8</risk_id>
    <assesment_factor>Awareness dan pemahaman Dewan Komisaris dan Direksi LJK mengenai manajemen Risiko kredit</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>501dc4eb-66d8-4092-90af-410d15919650</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>2025-12-01 10:03:15.017 +0700</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-01 10:03:15.017 +0700</updated_at>
    <updated_by>301</updated_by>
    <numeric_id>15</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>e53b25df-d7d4-43ad-9896-341b8dc54bcc</id>
    <code>SK01001003</code>
    <risk_id>8</risk_id>
    <assesment_factor>Budaya Risiko kredit dan internalisasi budaya Risiko pada LJK dalam Konglomerasi Keuangan</assesment_factor>
    <pic>{"value": "BANK,INSURANCE_COMPANY", "from_col": "COMPANY_TYPE"}</pic>
    <state>PUBLISHED</state>
    <tx_id>3e4fc744-1d02-40e9-9b74-c5e49c40890a</tx_id>
    <valid_from>2025-12-01 15:13:25.324 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-01 15:13:25.324 +0700</updated_at>
    <updated_by>301</updated_by>
    <numeric_id>16</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>66e6763b-686c-42a4-a288-dac16ce5a660</id>
    <code>SK01001003</code>
    <risk_id>8</risk_id>
    <assesment_factor>Budaya Risiko kredit dan internalisasi budaya Risiko pada LJK dalam Konglomerasi Keuangan</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>3e4fc744-1d02-40e9-9b74-c5e49c40890a</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>2025-12-01 15:13:25.328 +0700</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-01 15:13:25.328 +0700</updated_at>
    <updated_by>301</updated_by>
    <numeric_id>17</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>d36d8583-baf9-44f5-a924-a61acf83f8e1</id>
    <code>SK01004001</code>
    <risk_id>8</risk_id>
    <assesment_factor>Sistem pengendalian intern dalam mendukung pelaksanaan manajemen Risiko kredit</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>42f2c685-7a12-4152-8c67-1b2dc6f66b00</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>2025-12-07 22:41:07.650 +0700</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-07 22:41:07.650 +0700</updated_at>
    <updated_by>2</updated_by>
    <numeric_id>18</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>d3e8a770-d6a0-4afc-87a6-7bf98f091e28</id>
    <code>SK01001001</code>
    <risk_id>8</risk_id>
    <assesment_factor>Penetapan tingkat Risiko kredit yang akan diambil oleh LJK dan toleransi Risikonya sejalan dengan sasaran strategis dan strategi bisnis LJK secara keseluruhan</assesment_factor>
    <pic>{"value": "INSURANCE_COMPANY,1", "from_col": "INDIVIDUAL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>4040baf4-aba7-437a-a12d-8bcb1d75bfd0</tx_id>
    <valid_from>2025-12-08 09:07:36.601 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-08 09:07:36.601 +0700</updated_at>
    <updated_by>2</updated_by>
    <numeric_id>19</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>23053d80-b707-45cd-ba1b-e8db502b259b</id>
    <code>SK01001001</code>
    <risk_id>8</risk_id>
    <assesment_factor>Penetapan tingkat Risiko kredit yang akan diambil oleh LJK dan toleransi Risikonya sejalan dengan sasaran strategis dan strategi bisnis LJK secara keseluruhan</assesment_factor>
    <pic>{"value": "BANK,INSURANCE_COMPANY", "from_col": "COMPANY_TYPE"}</pic>
    <state>PUBLISHED</state>
    <tx_id>4040baf4-aba7-437a-a12d-8bcb1d75bfd0</tx_id>
    <valid_from>2025-12-01 09:30:27.791 +0700</valid_from>
    <valid_to>2025-12-08 09:07:36.604 +0700</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-08 09:07:36.604 +0700</updated_at>
    <updated_by>2</updated_by>
    <numeric_id>20</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>2cc264fd-0b88-48ad-a4d5-1eacbebf4384</id>
    <code>SK01004003</code>
    <risk_id>8</risk_id>
    <assesment_factor>Hasil kaji ulang independen terhadap penerapan Manajemen Risiko Terintegrasi untuk Risiko kredit</assesment_factor>
    <pic>{"value": "BANK", "from_col": "COMPANY_TYPE"}</pic>
    <state>PUBLISHED</state>
    <tx_id>1fd0dfff-a62e-4f84-b5f2-c24d4700a4cf</tx_id>
    <valid_from>2025-12-08 12:51:22.038 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-08 12:51:22.038 +0700</updated_at>
    <updated_by>2</updated_by>
    <numeric_id>21</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>6bd7e307-2449-46cb-aafe-2dbe6cffb4a3</id>
    <code>SK01004003</code>
    <risk_id>8</risk_id>
    <assesment_factor>Hasil kaji ulang independen terhadap penerapan Manajemen Risiko Terintegrasi untuk Risiko kredit</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>1fd0dfff-a62e-4f84-b5f2-c24d4700a4cf</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>2025-12-08 12:51:22.042 +0700</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-08 12:51:22.042 +0700</updated_at>
    <updated_by>2</updated_by>
    <numeric_id>22</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>dee9b671-99e3-4fb6-91a8-5e6b7e7d8b9b</id>
    <code>SK01004001</code>
    <risk_id>8</risk_id>
    <assesment_factor>Sistem pengendalian intern dalam mendukung pelaksanaan manajemen Risiko kredit</assesment_factor>
    <pic>{"value": "1,100", "from_col": "INDIVIDUAL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>42f2c685-7a12-4152-8c67-1b2dc6f66b00</tx_id>
    <valid_from>2025-12-08 12:52:46.950 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-08 12:52:46.950 +0700</updated_at>
    <updated_by>2</updated_by>
    <numeric_id>23</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>60bce2c4-b3b2-4473-b31b-747aecf2af95</id>
    <code>SK01001000</code>
    <risk_id>8</risk_id>
    <assesment_factor>Tata Kelola (Risk Governance)</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>fda094b0-1dbb-491e-a6e7-1d54773649e9</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>24</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>8aedf61d-279a-4b22-9837-fd5c2442c474</id>
    <code>SK01002000</code>
    <risk_id>8</risk_id>
    <assesment_factor>Kerangka Manajemen Risiko</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>e76a30df-269d-4661-beae-7beab3c7ebff</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>25</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>069c3c31-8179-4b96-ae4f-ed664b1a217a</id>
    <code>SK01003000</code>
    <risk_id>8</risk_id>
    <assesment_factor>Proses Manajemen Risiko, SIM dan SDM</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>3d88ef41-634a-4271-87b5-b3b3118d4790</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>26</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>c889e19d-aca4-4d2d-9742-dbd685a4788b</id>
    <code>SK01004000</code>
    <risk_id>8</risk_id>
    <assesment_factor>Sistem Pengendalian</assesment_factor>
    <pic>{"value": "*", "from_col": "ALL"}</pic>
    <state>PUBLISHED</state>
    <tx_id>6bd6e1eb-286b-4230-a934-ed91ce11be8f</tx_id>
    <valid_from>2025-11-28 11:44:31.712 +0700</valid_from>
    <valid_to>infinity</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-11-28 11:44:31.712 +0700</updated_at>
    <updated_by>SYSTEM</updated_by>
    <numeric_id>27</numeric_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>ca473347-c1cd-4fdb-9023-bdc328a5c6a1</id>
    <code>SK01004001</code>
    <risk_id>8</risk_id>
    <assesment_factor>Sistem pengendalian intern dalam mendukung pelaksanaan manajemen Risiko kredit</assesment_factor>
    <pic>{"value": "INSURANCE_COMPANY", "from_col": "COMPANY_TYPE"}</pic>
    <state>PUBLISHED</state>
    <tx_id>42f2c685-7a12-4152-8c67-1b2dc6f66b00</tx_id>
    <valid_from>2025-12-07 22:41:07.645 +0700</valid_from>
    <valid_to>2025-12-08 12:52:46.954 +0700</valid_to>
    <created_at>2025-11-28 11:44:31.712 +0700</created_at>
    <created_by>SYSTEM</created_by>
    <updated_at>2025-12-08 12:52:46.954 +0700</updated_at>
    <updated_by>2</updated_by>
    <numeric_id>28</numeric_id>
  </DATA_RECORD>
</kpmr_source>
