<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kpmr_risk_profile_edge [
  <!ELEMENT kpmr_risk_profile_edge (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (risiko_name?,Profile_ID?,Faktor_Penilaian?,derived_from_data_source_Risk_Profile?,Threshold?,input_system?,sandi_acuan_from_Data_Source_result_in_Rating?,Logic_Risk_Profile?,risk_id?,id?)+>
  <!ELEMENT risiko_name (#PCDATA)>
  <!ELEMENT Profile_ID (#PCDATA)>
  <!ELEMENT Faktor_Penilaian (#PCDATA)>
  <!ELEMENT derived_from_data_source_Risk_Profile (#PCDATA)>
  <!ELEMENT Threshold (#PCDATA)>
  <!ELEMENT input_system (#PCDATA)>
  <!ELEMENT sandi_acuan_from_Data_Source_result_in_Rating (#PCDATA)>
  <!ELEMENT Logic_Risk_Profile (#PCDATA)>
  <!ELEMENT risk_id (#PCDATA)>
  <!ELEMENT id (#PCDATA)>
]>
<kpmr_risk_profile_edge>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID></Profile_ID>
    <Faktor_Penilaian>Tata Kelola (Risk Governance)</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>Risk Profile</derived_from_data_source_Risk_Profile>
    <Threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating></sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>1</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01001001</Profile_ID>
    <Faktor_Penilaian>Penetapan tingkat Risiko kredit yang akan diambil oleh LJK dan toleransi Risikonya sejalan dengan sasaran strategis dan strategi bisnis LJK secara keseluruhan</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01001001</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>2</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01001002</Profile_ID>
    <Faktor_Penilaian>Awareness dan pemahaman Dewan Komisaris dan Direksi LJK mengenai manajemen Risiko kredit</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01001002</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>3</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01001003</Profile_ID>
    <Faktor_Penilaian>Budaya Risiko kredit dan internalisasi budaya Risiko pada LJK dalam Konglomerasi Keuangan</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01001003</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>4</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01001004</Profile_ID>
    <Faktor_Penilaian>Pelaksanaan tugas Dewan Komisaris dan Direksi LJK secara keseluruhan untuk Risiko kredit</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01001004</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>5</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID></Profile_ID>
    <Faktor_Penilaian>Kerangka Manajemen Risiko</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>Risk Profile</derived_from_data_source_Risk_Profile>
    <Threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating></sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>6</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01002001</Profile_ID>
    <Faktor_Penilaian>Fungsi Manajemen Risiko kredit pada LJK dalam Konglomerasi Keuangan memiliki tugas dan tanggung jawab yang jelas, serta telah berjalan independen</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01002001</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>7</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01002002</Profile_ID>
    <Faktor_Penilaian>Strategi perkreditan atau pembiayaan dan kesesuaiannya dengan tingkat Risiko yang akan diambil dan toleransi Risiko kredit</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01002002</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>8</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01002003</Profile_ID>
    <Faktor_Penilaian>Terdapat kebijakan, prosedur, dan limit Risiko kredit untuk seluruh area manajemen Risiko kredit Kyang diterapkan dan dipahami</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01002003</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>9</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID></Profile_ID>
    <Faktor_Penilaian>Proses Manajemen Risiko, SIM dan SDM</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>Risk Profile</derived_from_data_source_Risk_Profile>
    <Threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating></sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>10</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01003001</Profile_ID>
    <Faktor_Penilaian>Proses manajemen Risiko kredit oleh LJK dalam Konglomerasi Keuangan dalam mengidentifikasi, mengukur, memantau, dan mengendalikan Risiko kredit</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01003001</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>11</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01003002</Profile_ID>
    <Faktor_Penilaian>Proses penyediaan dana oleh LJK dalam Konglomerasi Keuangan mulai dari proses analisis hingga penanganan aset bermasalah</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01003002</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>12</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01003003</Profile_ID>
    <Faktor_Penilaian>Sistem pemeringkatan Risiko kredit diterapkan secara konsisten, dan dipahami dengan baik oleh seluruh LJK dalam Konglomerasi Keuangan</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01003003</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>13</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01003004</Profile_ID>
    <Faktor_Penilaian>Terdapat Sistem Informasi Manajemen Terintegrasi (SIMT) untuk Risiko kredit sehingga menghasilkan pelaporan Risiko kredit Konglomerasi Keuangan secara keseluruhan yang komprehensif dan terintegrasi</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01003004</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>14</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01003005</Profile_ID>
    <Faktor_Penilaian>Pemenuhan sumber daya manusia pada LJK dalam Konglomerasi Keuangan baik dari sisi kuantitas maupun kompetensi pada fungsi manajemen Risiko kredit</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01003005</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>15</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID></Profile_ID>
    <Faktor_Penilaian>Sistem Pengendalian</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>Risk Profile</derived_from_data_source_Risk_Profile>
    <Threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating></sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>16</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01004001</Profile_ID>
    <Faktor_Penilaian>Sistem pengendalian intern dalam mendukung pelaksanaan manajemen Risiko kredit</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01004001</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>17</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01004002</Profile_ID>
    <Faktor_Penilaian>Pelaksanaan kaji ulang secara independen (independent review) untuk Risiko kredit oleh SKAIT baik dari sisi metodologi, frekuensi, maupun pelaporan kepada Dewan Komisaris dan Direksi LJK</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01004002</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>18</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01004003</Profile_ID>
    <Faktor_Penilaian>Hasil kaji ulang independen terhadap penerapan Manajemen Risiko Terintegrasi untuk Risiko kredit</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01004003</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>19</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID>RK01004004</Profile_ID>
    <Faktor_Penilaian>Pelaksanaan tindak lanjut atas hasil kaji ulang independen untuk Risiko kredit</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK01004004</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>20</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID></Profile_ID>
    <Faktor_Penilaian>Total Score and Rating</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>Risk Profile</derived_from_data_source_Risk_Profile>
    <Threshold>5 : Score &lt;= 40
4:  40 &lt; Score &lt;= 55
3:  55 &lt; Score &lt;= 70
2:  70 &lt; Score &lt;= 85
1:  85 &lt; Score &lt;= 100</Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating></sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Score : Total SxB from the risk profile with color Gray
Rating : Score vs Threshold</Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>21</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Kredit</risiko_name>
    <Profile_ID></Profile_ID>
    <Faktor_Penilaian></Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile></derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system></input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating></sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile></Logic_Risk_Profile>
    <risk_id>8</risk_id>
    <id>22</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID></Profile_ID>
    <Faktor_Penilaian>Tata Kelola (Risk Governance)</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>Risk Profile</derived_from_data_source_Risk_Profile>
    <Threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating></sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>23</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID>RK02001001</Profile_ID>
    <Faktor_Penilaian>Penetapan tingkat Risiko Pasar yang akan diambil oleh LJK dan toleransi Risikonya sejalan dengan sasaran strategis dan strategi bisnis LJK secara keseluruhan</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK02001001</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>24</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID>RK02001002</Profile_ID>
    <Faktor_Penilaian>Awareness dan pemahaman Dewan Komisaris dan Direksi LJK mengenai manajemen Risiko Pasar</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK02001002</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>25</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID>RK02001003</Profile_ID>
    <Faktor_Penilaian>Budaya Risiko Pasar dan internalisasi budaya Risiko pada LJK dalam Konglomerasi Keuangan</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK02001003</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>26</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID>RK02001004</Profile_ID>
    <Faktor_Penilaian>Pelaksanaan tugas Dewan Komisaris dan Direksi LJK secara keseluruhan untuk Risiko Pasar</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK02001004</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>27</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID></Profile_ID>
    <Faktor_Penilaian>Kerangka Manajemen Risiko</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>Risk Profile</derived_from_data_source_Risk_Profile>
    <Threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating></sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>28</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID>RK02002001</Profile_ID>
    <Faktor_Penilaian>Fungsi Manajemen Risiko Pasar pada LJK dalam Konglomerasi Keuangan memiliki tugas dan tanggung jawab yang jelas, serta telah berjalan independen</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK02002001</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>29</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID>RK02002002</Profile_ID>
    <Faktor_Penilaian>Strategi pengelolaan Risiko pasar Konglomerasi Keuangan termasuk strategi trading dan pengelolaan posisi non-trading book.</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK02002002</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>30</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID>RK02002003</Profile_ID>
    <Faktor_Penilaian>Terdapat kebijakan, prosedur, dan limit Risiko Pasar untuk seluruh area manajemen Risiko Pasar yang diterapkan dan dipahami</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK02002003</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>31</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID></Profile_ID>
    <Faktor_Penilaian>Proses Manajemen Risiko, SIM dan SDM</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>Risk Profile</derived_from_data_source_Risk_Profile>
    <Threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating></sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>32</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID>RK02003001</Profile_ID>
    <Faktor_Penilaian>Proses manajemen Risiko Pasar oleh LJK dalam Konglomerasi Keuangan dalam mengidentifikasi, mengukur, memantau, dan mengendalikan Risiko Pasar</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK02003001</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>33</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID>RK02003002</Profile_ID>
    <Faktor_Penilaian>Terdapat Sistem Informasi Manajemen Terintegrasi (SIMT) untuk Risiko Pasar sehingga menghasilkan pelaporan Risiko Pasar Konglomerasi Keuangan secara keseluruhan yang komprehensif dan terintegrasi</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK02003002</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>34</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID>RK02003003</Profile_ID>
    <Faktor_Penilaian>Pemenuhan sumber daya manusia pada LJK dalam Konglomerasi Keuangan baik dari sisi kuantitas maupun kompetensi pada fungsi manajemen Risiko Pasar</Faktor_Penilaian>
    <derived_from_data_source_Risk_Profile>data source</derived_from_data_source_Risk_Profile>
    <Threshold></Threshold>
    <input_system>system</input_system>
    <sandi_acuan_from_Data_Source_result_in_Rating>SK02003003</sandi_acuan_from_Data_Source_result_in_Rating>
    <Logic_Risk_Profile>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</Logic_Risk_Profile>
    <risk_id>9</risk_id>
    <id>35</id>
  </DATA_RECORD>
  <DATA_RECORD>
    <risiko_name>Risiko Pasar</risiko_name>
    <Profile_ID></Profile_ID>